#端口号
server:
  port: 8880
info:
  app:
    name:provider-user-metadata
  java:
    source:1.8.0_121
    target:1.8.0_121
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我自定义的元数据2       # 自定义的元数据，key/value都可以随便写。

#数据库的配置信息
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 169.254
  application:
    name: provider-user
  datasource:
    name: wyzDataSource
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: mshtAPP
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 30
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath:mappers/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  #type-aliases-package: com.wyz.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl