eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8777
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/WuYanZhong/configserver-repo.git
          username: 449190067@qq.com
          password: zhong45hao88
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

