spring:
  application:
    name: eureka-ha
---
spring:
  profiles: eureka1                                 # 指定profile=eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1                               # 指定当profile=eureka1时，主机名是eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/      # 将自己注册到eureka2这个Eureka上面去

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/